// Static markup cut from Node's React Email output (fixtures/node-renders.json) by
// splitting around the dynamic text; see templates.rs. Regenerate rather than edit.
const HEAD: &str = "<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\"><html dir=\"ltr\" lang=\"en\"><head><link rel=\"preload\" as=\"image\" href=\"https://app.hygo.ai/hygo/horizontal_black.svg\"/><meta content=\"text/html; charset=UTF-8\" http-equiv=\"Content-Type\"/><meta name=\"x-apple-disable-message-reformatting\"/></head><body style=\"background-color:rgb(255,255,255)\"><!--$--><!--html--><!--head--><div style=\"display:none;overflow:hidden;line-height:1px;opacity:0;max-height:0;max-width:0\" data-skip-in-text=\"true\">";
const OTP_AFTER_PREVIEW: &str = "</div><!--body--><table border=\"0\" width=\"100%\" cellPadding=\"0\" cellSpacing=\"0\" role=\"presentation\" align=\"center\"><tbody><tr><td style=\"background-color:rgb(255,255,255);font-family:ui-sans-serif,system-ui,sans-serif,&quot;Apple Color Emoji&quot;,&quot;Segoe UI Emoji&quot;,&quot;Segoe UI Symbol&quot;,&quot;Noto Color Emoji&quot;\"><table align=\"center\" width=\"100%\" border=\"0\" cellPadding=\"0\" cellSpacing=\"0\" role=\"presentation\" style=\"max-width:600px;margin-right:auto;margin-left:auto;padding-bottom:32px;padding-top:32px;padding-right:24px;padding-left:24px\"><tbody><tr style=\"width:100%\"><td><img alt=\"Hygo\" height=\"28\" src=\"https://app.hygo.ai/hygo/horizontal_black.svg\" style=\"display:block;outline:none;border:none;text-decoration:none;margin-bottom:32px\" width=\"120\"/><p style=\"font-size:16px;line-height:1.625;color:rgb(17,24,39);margin-bottom:16px;margin-top:16px\">Hi there,</p><p style=\"font-size:16px;line-height:1.625;color:rgb(17,24,39);margin-bottom:16px;margin-top:16px\">";
const OTP_AFTER_DESCRIPTION: &str = "</p><table align=\"center\" width=\"100%\" border=\"0\" cellPadding=\"0\" cellSpacing=\"0\" role=\"presentation\" style=\"text-align:center;margin-bottom:24px\"><tbody><tr><td><div style=\"background-color:rgb(249,250,251);padding-bottom:20px;padding-top:20px;padding-right:24px;padding-left:24px;border-radius:0.375rem;display:inline-block\"><p style=\"font-size:30px;line-height:36px;color:rgb(16,185,129);font-weight:700;letter-spacing:0.1em;margin:0;margin-top:0;margin-bottom:0;margin-left:0;margin-right:0\">";
const OTP_AFTER_CODE: &str = "</p></div></td></tr></tbody></table><p style=\"font-size:14px;line-height:1.625;color:rgb(107,114,128);margin-bottom:8px;margin-top:16px\">This code will expire in 5 minutes.</p><p style=\"font-size:14px;line-height:1.625;color:rgb(107,114,128);margin-top:16px;margin-bottom:16px\">If you didn&#x27;t request this code, you can safely ignore this email.</p><hr style=\"width:100%;border:none;border-top:1px solid #eaeaea;border-color:rgb(229,231,235);margin-bottom:32px;margin-top:32px\"/><p style=\"font-size:12px;line-height:16px;color:rgb(107,114,128);margin-top:16px;margin-bottom:16px\">© <!-- -->";
const TAIL: &str = "<!-- --> Hygo Analytics</p></td></tr></tbody></table></td></tr></tbody></table><!--/$--></body></html>";
const INVITE_AFTER_PREVIEW: &str = "</div><!--body--><table border=\"0\" width=\"100%\" cellPadding=\"0\" cellSpacing=\"0\" role=\"presentation\" align=\"center\"><tbody><tr><td style=\"background-color:rgb(255,255,255);font-family:ui-sans-serif,system-ui,sans-serif,&quot;Apple Color Emoji&quot;,&quot;Segoe UI Emoji&quot;,&quot;Segoe UI Symbol&quot;,&quot;Noto Color Emoji&quot;\"><table align=\"center\" width=\"100%\" border=\"0\" cellPadding=\"0\" cellSpacing=\"0\" role=\"presentation\" style=\"max-width:600px;margin-right:auto;margin-left:auto;padding-bottom:32px;padding-top:32px;padding-right:24px;padding-left:24px\"><tbody><tr style=\"width:100%\"><td><img alt=\"Hygo\" height=\"28\" src=\"https://app.hygo.ai/hygo/horizontal_black.svg\" style=\"display:block;outline:none;border:none;text-decoration:none;margin-bottom:32px\" width=\"120\"/><p style=\"font-size:16px;line-height:1.625;color:rgb(17,24,39);margin-bottom:16px;margin-top:16px\">Hi there,</p><p style=\"font-size:16px;line-height:1.625;color:rgb(17,24,39);margin-bottom:16px;margin-top:16px\">";
const INVITE_AFTER_INVITER: &str = "<!-- --> has invited you to join <span style=\"font-weight:600\">";
const INVITE_AFTER_ORGANIZATION: &str = "</span> on Hygo Analytics.</p><p style=\"font-size:16px;line-height:1.625;color:rgb(17,24,39);margin-bottom:16px;margin-top:16px\">Hygo is an open-source analytics platform that helps you understand your website traffic while respecting user privacy.</p><p style=\"font-size:16px;line-height:1.625;color:rgb(17,24,39);margin-bottom:16px;margin-top:16px\"><a href=\"";
const INVITE_AFTER_LINK: &str = "\" style=\"color:rgb(16,185,129);text-decoration-line:underline\" target=\"_blank\">Accept the invitation</a></p><p style=\"font-size:14px;line-height:1.625;color:rgb(107,114,128);margin-top:16px;margin-bottom:16px\">This invitation was sent to <!-- -->";
const INVITE_AFTER_EMAIL: &str = "<!-- -->.</p><hr style=\"width:100%;border:none;border-top:1px solid #eaeaea;border-color:rgb(229,231,235);margin-bottom:32px;margin-top:32px\"/><p style=\"font-size:12px;line-height:16px;color:rgb(107,114,128);margin-top:16px;margin-bottom:16px\">© <!-- -->";
