//! Tracking payload validation, channel attribution, URL helpers, client IP
//! resolution and site exclusions, ported from server/src/services/tracker,
//! server/src/services/sites/siteExclusionDecision.ts and server/src/lib/ipUtils.ts.
//!
//! Everything here is pure (no stores), so ingest routes can call it from any
//! handler. Parity with Node is checked two ways: the ported vitest suites live next
//! to each module, and `parity_tests` replays inputs whose Node outputs were dumped
//! by scripts run against the real TypeScript (see that module for how to run them).
#![allow(dead_code)] // consumed by /api/track, /api/identify and replay ingest as they are ported

pub mod body;
pub mod channel;
// Generated by parity/tracking/gen_channel_lists.ts, one entry per line
#[rustfmt::skip]
mod channel_lists;
pub mod client_ip;
pub mod exclusions;
pub mod ip_utils;
pub mod js;
pub mod json;
pub mod payload;
pub mod url_params;

#[cfg(test)]
mod parity_tests;

use std::net::IpAddr;

// The entry points ingest handlers use; unused until those handlers land
#[allow(unused_imports)]
pub use body::{
    BodyHeaders, BodyRejection, TRACK_BODY_LIMIT_BYTES, body_too_large, parse_track_body, reject_before_reading,
};
#[allow(unused_imports)]
pub use channel::get_channel;
#[allow(unused_imports)]
pub use client_ip::{collect_candidate_client_ips, get_ip_address, get_request_user_agent, resolve_client_ip};
#[allow(unused_imports)]
pub use exclusions::{
    SiteExclusionDecision, SiteExclusionReason, SiteExclusionRequest, SiteExclusionRules, decide_site_exclusion,
};
#[allow(unused_imports)]
pub use ip_utils::{IpPatternValidation, matches_cidr, matches_range, validate_ip_pattern};
#[allow(unused_imports)]
pub use json::JsValue;
#[allow(unused_imports)]
pub use payload::{PayloadErrors, TrackingEventType, ValidatedTrackingPayload, validate_tracking_payload};
#[allow(unused_imports)]
pub use url_params::{clear_self_referrer, get_all_url_params, get_utm_params};

use crate::geo::{AsnInfo, AsnLookup, Geo};

/// Node's `AsnLookup` function type: anything that can answer "which ASN is this IP".
/// Production passes the request-scoped [`AsnLookup`]; tests pass fakes.
pub trait AsnSource {
    fn asn_info(&self, ip: &str) -> Option<AsnInfo>;

    fn asn_number(&self, ip: &str) -> Option<u32> {
        self.asn_info(ip).map(|info| info.asn)
    }
}

/// The part of `getLocation` exclusions need.
pub trait LocationSource {
    fn country_iso(&self, ip: &str) -> Option<String>;
}

/// @maxmind/geoip2-node refuses anything `net.isIP` rejects (surrounding whitespace
/// included) before looking it up, while `Geo` trims first; gate on a strict parse so
/// odd header values miss here as they do in Node.
fn is_lookup_candidate(ip: &str) -> bool {
    ip.parse::<IpAddr>().is_ok()
}

impl AsnSource for AsnLookup<'_> {
    fn asn_info(&self, ip: &str) -> Option<AsnInfo> {
        if !is_lookup_candidate(ip) {
            return None;
        }
        self.lookup(ip)
    }
}

impl AsnSource for Geo {
    fn asn_info(&self, ip: &str) -> Option<AsnInfo> {
        if !is_lookup_candidate(ip) {
            return None;
        }
        self.asn(ip)
    }
}

impl LocationSource for Geo {
    fn country_iso(&self, ip: &str) -> Option<String> {
        if !is_lookup_candidate(ip) {
            return None;
        }
        self.location(ip)?.country_iso
    }
}
