//! Regex tables of ua-parser-js 2.0.3 (`defaultRegexes`), 295 patterns.
//!
//! GENERATED by tools/generate.cjs from the ua-parser.js the Node server runs; do not
//! edit by hand. Patterns are the JS sources verbatim (all compiled with the `i`
//! flag); mod.rs translates them. Rules are in the order rgxMapper tries them.
#![cfg_attr(rustfmt, rustfmt_skip)]

use super::table::{Field::*, Prop::*, Rep, RuleSrc, StrMap};

pub(super) static BROWSER: &[RuleSrc] = &[
    RuleSrc {
        patterns: &[
            r#"\b(?:crmo|crios)\/([\w\.]+)"#,
        ],
        props: &[Capture(Version), Const(Name, "Mobile Chrome")],
    },
    RuleSrc {
        patterns: &[
            r#"edg(?:e|ios|a)?\/([\w\.]+)"#,
        ],
        props: &[Capture(Version), Const(Name, "Edge")],
    },
    RuleSrc {
        patterns: &[
            r#"(opera mini)\/([-\w\.]+)"#,
            r#"(opera [mobiletab]{3,6})\b.+version\/([-\w\.]+)"#,
            r#"(opera)(?:.+version\/|[\/ ]+)([\w\.]+)"#,
        ],
        props: &[Capture(Name), Capture(Version)],
    },
    RuleSrc {
        patterns: &[
            r#"opios[\/ ]+([\w\.]+)"#,
        ],
        props: &[Capture(Version), Const(Name, "Opera Mini")],
    },
    RuleSrc {
        patterns: &[
            r#"\bop(?:rg)?x\/([\w\.]+)"#,
        ],
        props: &[Capture(Version), Const(Name, "Opera GX")],
    },
    RuleSrc {
        patterns: &[
            r#"\bopr\/([\w\.]+)"#,
        ],
        props: &[Capture(Version), Const(Name, "Opera")],
    },
    RuleSrc {
        patterns: &[
            r#"\bb[ai]*d(?:uhd|[ub]*[aekoprswx]{5,6})[\/ ]?([\w\.]+)"#,
        ],
        props: &[Capture(Version), Const(Name, "Baidu")],
    },
    RuleSrc {
        patterns: &[
            r#"\b(?:mxbrowser|mxios|myie2)\/?([-\w\.]*)\b"#,
        ],
        props: &[Capture(Version), Const(Name, "Maxthon")],
    },
    RuleSrc {
        patterns: &[
            r#"(kindle)\/([\w\.]+)"#,
            r#"(lunascape|maxthon|netfront|jasmine|blazer|sleipnir)[\/ ]?([\w\.]*)"#,
            r#"(avant|iemobile|slim(?:browser|boat|jet))[\/ ]?([\d\.]*)"#,
            r#"(?:ms|\()(ie) ([\w\.]+)"#,
            r#"(flock|rockmelt|midori|epiphany|silk|skyfire|ovibrowser|bolt|iron|vivaldi|iridium|phantomjs|bowser|qupzilla|falkon|rekonq|puffin|brave|whale(?!.+naver)|qqbrowserlite|duckduckgo|klar|helio|(?=comodo_)?dragon|otter|dooble|(?:lg |qute)browser)\/([-\w\.]+)"#,
            r#"(heytap|ovi|115|surf)browser\/([\d\.]+)"#,
            r#"(ecosia|weibo)(?:__| \w+@)([\d\.]+)"#,
        ],
        props: &[Capture(Name), Capture(Version)],
    },
    RuleSrc {
        patterns: &[
            r#"quark(?:pc)?\/([-\w\.]+)"#,
        ],
        props: &[Capture(Version), Const(Name, "Quark")],
    },
    RuleSrc {
        patterns: &[
            r#"\bddg\/([\w\.]+)"#,
        ],
        props: &[Capture(Version), Const(Name, "DuckDuckGo")],
    },
    RuleSrc {
        patterns: &[
            r#"(?:\buc? ?browser|(?:juc.+)ucweb)[\/ ]?([\w\.]+)"#,
        ],
        props: &[Capture(Version), Const(Name, "UCBrowser")],
    },
    RuleSrc {
        patterns: &[
            r#"microm.+\bqbcore\/([\w\.]+)"#,
            r#"\bqbcore\/([\w\.]+).+microm"#,
            r#"micromessenger\/([\w\.]+)"#,
        ],
        props: &[Capture(Version), Const(Name, "WeChat")],
    },
    RuleSrc {
        patterns: &[
            r#"konqueror\/([\w\.]+)"#,
        ],
        props: &[Capture(Version), Const(Name, "Konqueror")],
    },
    RuleSrc {
        patterns: &[
            r#"trident.+rv[: ]([\w\.]{1,9})\b.+like gecko"#,
        ],
        props: &[Capture(Version), Const(Name, "IE")],
    },
    RuleSrc {
        patterns: &[
            r#"ya(?:search)?browser\/([\w\.]+)"#,
        ],
        props: &[Capture(Version), Const(Name, "Yandex")],
    },
    RuleSrc {
        patterns: &[
            r#"slbrowser\/([\w\.]+)"#,
        ],
        props: &[Capture(Version), Const(Name, "Smart Lenovo Browser")],
    },
    RuleSrc {
        patterns: &[
            r#"(avast|avg)\/([\w\.]+)"#,
        ],
        props: &[Replace(Name, Rep::WrapLines { prefix: "", suffix: " Secure Browser", global: false }), Capture(Version)],
    },
    RuleSrc {
        patterns: &[
            r#"\bfocus\/([\w\.]+)"#,
        ],
        props: &[Capture(Version), Const(Name, "Firefox Focus")],
    },
    RuleSrc {
        patterns: &[
            r#"\bopt\/([\w\.]+)"#,
        ],
        props: &[Capture(Version), Const(Name, "Opera Touch")],
    },
    RuleSrc {
        patterns: &[
            r#"coc_coc\w+\/([\w\.]+)"#,
        ],
        props: &[Capture(Version), Const(Name, "Coc Coc")],
    },
    RuleSrc {
        patterns: &[
            r#"dolfin\/([\w\.]+)"#,
        ],
        props: &[Capture(Version), Const(Name, "Dolphin")],
    },
    RuleSrc {
        patterns: &[
            r#"coast\/([\w\.]+)"#,
        ],
        props: &[Capture(Version), Const(Name, "Opera Coast")],
    },
    RuleSrc {
        patterns: &[
            r#"miuibrowser\/([\w\.]+)"#,
        ],
        props: &[Capture(Version), Const(Name, "MIUI Browser")],
    },
    RuleSrc {
        patterns: &[
            r#"fxios\/([\w\.-]+)"#,
        ],
        props: &[Capture(Version), Const(Name, "Mobile Firefox")],
    },
    RuleSrc {
        patterns: &[
            r#"\bqihoobrowser\/?([\w\.]*)"#,
        ],
        props: &[Capture(Version), Const(Name, "360")],
    },
    RuleSrc {
        patterns: &[
            r#"\b(qq)\/([\w\.]+)"#,
        ],
        props: &[Replace(Name, Rep::WrapLines { prefix: "", suffix: "Browser", global: false }), Capture(Version)],
    },
    RuleSrc {
        patterns: &[
            r#"(oculus|sailfish|huawei|vivo|pico)browser\/([\w\.]+)"#,
        ],
        props: &[Replace(Name, Rep::WrapLines { prefix: "", suffix: " Browser", global: false }), Capture(Version)],
    },
    RuleSrc {
        patterns: &[
            r#"samsungbrowser\/([\w\.]+)"#,
        ],
        props: &[Capture(Version), Const(Name, "Samsung Internet")],
    },
    RuleSrc {
        patterns: &[
            r#"metasr[\/ ]?([\d\.]+)"#,
        ],
        props: &[Capture(Version), Const(Name, "Sogou Explorer")],
    },
    RuleSrc {
        patterns: &[
            r#"(sogou)mo\w+\/([\d\.]+)"#,
        ],
        props: &[Const(Name, "Sogou Mobile"), Capture(Version)],
    },
    RuleSrc {
        patterns: &[
            r#"(electron)\/([\w\.]+) safari"#,
            r#"(tesla)(?: qtcarbrowser|\/(20\d\d\.[-\w\.]+))"#,
            r#"m?(qqbrowser|2345(?=browser|chrome|explorer))\w*[\/ ]?v?([\w\.]+)"#,
        ],
        props: &[Capture(Name), Capture(Version)],
    },
    RuleSrc {
        patterns: &[
            r#"(lbbrowser|rekonq)"#,
        ],
        props: &[Capture(Name)],
    },
    RuleSrc {
        patterns: &[
            r#"ome\/([\w\.]+) \w* ?(iron) saf"#,
            r#"ome\/([\w\.]+).+qihu (360)[es]e"#,
        ],
        props: &[Capture(Version), Capture(Name)],
    },
    RuleSrc {
        patterns: &[
            r#"((?:fban\/fbios|fb_iab\/fb4a)(?!.+fbav)|;fbav\/([\w\.]+);)"#,
        ],
        props: &[Const(Name, "Facebook"), Capture(Version), Const(Type, "inapp")],
    },
    RuleSrc {
        patterns: &[
            r#"(Klarna)\/([\w\.]+)"#,
            r#"(kakao(?:talk|story))[\/ ]([\w\.]+)"#,
            r#"(naver)\(.*?(\d+\.[\w\.]+).*\)"#,
            r#"(daum)apps[\/ ]([\w\.]+)"#,
            r#"safari (line)\/([\w\.]+)"#,
            r#"\b(line)\/([\w\.]+)\/iab"#,
            r#"(alipay)client\/([\w\.]+)"#,
            r#"(twitter)(?:and| f.+e\/([\w\.]+))"#,
            r#"(instagram|snapchat)[\/ ]([-\w\.]+)"#,
        ],
        props: &[Capture(Name), Capture(Version), Const(Type, "inapp")],
    },
    RuleSrc {
        patterns: &[
            r#"\bgsa\/([\w\.]+) .*safari\/"#,
        ],
        props: &[Capture(Version), Const(Name, "GSA"), Const(Type, "inapp")],
    },
    RuleSrc {
        patterns: &[
            r#"musical_ly(?:.+app_?version\/|_)([\w\.]+)"#,
        ],
        props: &[Capture(Version), Const(Name, "TikTok"), Const(Type, "inapp")],
    },
    RuleSrc {
        patterns: &[
            r#"\[(linkedin)app\]"#,
        ],
        props: &[Capture(Name), Const(Type, "inapp")],
    },
    RuleSrc {
        patterns: &[
            r#"(chromium)[\/ ]([-\w\.]+)"#,
        ],
        props: &[Capture(Name), Capture(Version)],
    },
    RuleSrc {
        patterns: &[
            r#"headlesschrome(?:\/([\w\.]+)| )"#,
        ],
        props: &[Capture(Version), Const(Name, "Chrome Headless")],
    },
    RuleSrc {
        patterns: &[
            r#" wv\).+(chrome)\/([\w\.]+)"#,
        ],
        props: &[Const(Name, "Chrome WebView"), Capture(Version)],
    },
    RuleSrc {
        patterns: &[
            r#"droid.+ version\/([\w\.]+)\b.+(?:mobile safari|safari)"#,
        ],
        props: &[Capture(Version), Const(Name, "Android Browser")],
    },
    RuleSrc {
        patterns: &[
            r#"chrome\/([\w\.]+) mobile"#,
        ],
        props: &[Capture(Version), Const(Name, "Mobile Chrome")],
    },
    RuleSrc {
        patterns: &[
            r#"(chrome|omniweb|arora|[tizenoka]{5} ?browser)\/v?([\w\.]+)"#,
        ],
        props: &[Capture(Name), Capture(Version)],
    },
    RuleSrc {
        patterns: &[
            r#"version\/([\w\.\,]+) .*mobile(?:\/\w+ | ?)safari"#,
        ],
        props: &[Capture(Version), Const(Name, "Mobile Safari")],
    },
    RuleSrc {
        patterns: &[
            r#"iphone .*mobile(?:\/\w+ | ?)safari"#,
        ],
        props: &[Const(Name, "Mobile Safari")],
    },
    RuleSrc {
        patterns: &[
            r#"version\/([\w\.\,]+) .*(safari)"#,
        ],
        props: &[Capture(Version), Capture(Name)],
    },
    RuleSrc {
        patterns: &[
            r#"webkit.+?(mobile ?safari|safari)(\/[\w\.]+)"#,
        ],
        props: &[Capture(Name), Const(Version, "1")],
    },
    RuleSrc {
        patterns: &[
            r#"(webkit|khtml)\/([\w\.]+)"#,
        ],
        props: &[Capture(Name), Capture(Version)],
    },
    RuleSrc {
        patterns: &[
            r#"(?:mobile|tablet);.*(firefox)\/([\w\.-]+)"#,
        ],
        props: &[Const(Name, "Mobile Firefox"), Capture(Version)],
    },
    RuleSrc {
        patterns: &[
            r#"(navigator|netscape\d?)\/([-\w\.]+)"#,
        ],
        props: &[Const(Name, "Netscape"), Capture(Version)],
    },
    RuleSrc {
        patterns: &[
            r#"(wolvic|librewolf)\/([\w\.]+)"#,
        ],
        props: &[Capture(Name), Capture(Version)],
    },
    RuleSrc {
        patterns: &[
            r#"mobile vr; rv:([\w\.]+)\).+firefox"#,
        ],
        props: &[Capture(Version), Const(Name, "Firefox Reality")],
    },
    RuleSrc {
        patterns: &[
            r#"ekiohf.+(flow)\/([\w\.]+)"#,
            r#"(swiftfox)"#,
            r#"(icedragon|iceweasel|camino|chimera|fennec|maemo browser|minimo|conkeror)[\/ ]?([\w\.\+]+)"#,
            r#"(seamonkey|k-meleon|icecat|iceape|firebird|phoenix|palemoon|basilisk|waterfox)\/([-\w\.]+)$"#,
            r#"(firefox)\/([\w\.]+)"#,
            r#"(mozilla)\/([\w\.]+) .+rv\:.+gecko\/\d+"#,
            r#"(amaya|dillo|doris|icab|ladybird|lynx|mosaic|netsurf|obigo|polaris|w3m|(?:go|ice|up)[\. ]?browser)[-\/ ]?v?([\w\.]+)"#,
            r#"\b(links) \(([\w\.]+)"#,
        ],
        props: &[Capture(Name), Replace(Version, Rep::ReplaceAll { from: '_', to: "." })],
    },
    RuleSrc {
        patterns: &[
            r#"(cobalt)\/([\w\.]+)"#,
        ],
        props: &[Capture(Name), Replace(Version, Rep::StripFirstNonVersionRun)],
    },
];

pub(super) static CPU: &[RuleSrc] = &[
    RuleSrc {
        patterns: &[
            r#"\b((amd|x|x86[-_]?|wow|win)64)\b"#,
        ],
        props: &[Const(Architecture, "amd64")],
    },
    RuleSrc {
        patterns: &[
            r#"(ia32(?=;))"#,
            r#"\b((i[346]|x)86)(pc)?\b"#,
        ],
        props: &[Const(Architecture, "ia32")],
    },
    RuleSrc {
        patterns: &[
            r#"\b(aarch64|arm(v?[89]e?l?|_?64))\b"#,
        ],
        props: &[Const(Architecture, "arm64")],
    },
    RuleSrc {
        patterns: &[
            r#"\b(arm(v[67])?ht?n?[fl]p?)\b"#,
        ],
        props: &[Const(Architecture, "armhf")],
    },
    RuleSrc {
        patterns: &[
            r#"( (ce|mobile); ppc;|\/[\w\.]+arm\b)"#,
        ],
        props: &[Const(Architecture, "arm")],
    },
    RuleSrc {
        patterns: &[
            r#"((ppc|powerpc)(64)?)( mac|;|\))"#,
        ],
        props: &[ReplaceLower(Architecture, Rep::RemoveFirst("ower"))],
    },
    RuleSrc {
        patterns: &[
            r#" sun4\w[;\)]"#,
        ],
        props: &[Const(Architecture, "sparc")],
    },
    RuleSrc {
        patterns: &[
            r#"\b(avr32|ia64(?=;)|68k(?=\))|\barm(?=v([1-7]|[5-7]1)l?|;|eabi)|(irix|mips|sparc)(64)?\b|pa-risc)"#,
        ],
        props: &[Lower(Architecture)],
    },
];

pub(super) static DEVICE: &[RuleSrc] = &[
    RuleSrc {
        patterns: &[
            r#"\b(sch-i[89]0\d|shw-m380s|sm-[ptx]\w{2,4}|gt-[pn]\d{2,4}|sgh-t8[56]9|nexus 10)"#,
        ],
        props: &[Capture(Model), Const(Vendor, "Samsung"), Const(Type, "tablet")],
    },
    RuleSrc {
        patterns: &[
            r#"\b((?:s[cgp]h|gt|sm)-(?![lr])\w+|sc[g-]?[\d]+a?|galaxy nexus)"#,
            r#"samsung[- ]((?!sm-[lr])[-\w]+)"#,
            r#"sec-(sgh\w+)"#,
        ],
        props: &[Capture(Model), Const(Vendor, "Samsung"), Const(Type, "mobile")],
    },
    RuleSrc {
        patterns: &[
            r#"(?:\/|\()(ip(?:hone|od)[\w, ]*)(?:\/|;)"#,
        ],
        props: &[Capture(Model), Const(Vendor, "Apple"), Const(Type, "mobile")],
    },
    RuleSrc {
        patterns: &[
            r#"\((ipad);[-\w\),; ]+apple"#,
            r#"applecoremedia\/[\w\.]+ \((ipad)"#,
            r#"\b(ipad)\d\d?,\d\d?[;\]].+ios"#,
        ],
        props: &[Capture(Model), Const(Vendor, "Apple"), Const(Type, "tablet")],
    },
    RuleSrc {
        patterns: &[
            r#"(macintosh);"#,
        ],
        props: &[Capture(Model), Const(Vendor, "Apple")],
    },
    RuleSrc {
        patterns: &[
            r#"\b(sh-?[altvz]?\d\d[a-ekm]?)"#,
        ],
        props: &[Capture(Model), Const(Vendor, "Sharp"), Const(Type, "mobile")],
    },
    RuleSrc {
        patterns: &[
            r#"\b((?:brt|eln|hey2?|gdi|jdn)-a?[lnw]09|(?:ag[rm]3?|jdn2|kob2)-a?[lw]0[09]hn)(?: bui|\)|;)"#,
        ],
        props: &[Capture(Model), Const(Vendor, "Honor"), Const(Type, "tablet")],
    },
    RuleSrc {
        patterns: &[
            r#"honor([-\w ]+)[;\)]"#,
        ],
        props: &[Capture(Model), Const(Vendor, "Honor"), Const(Type, "mobile")],
    },
    RuleSrc {
        patterns: &[
            r#"\b((?:ag[rs][2356]?k?|bah[234]?|bg[2o]|bt[kv]|cmr|cpn|db[ry]2?|jdn2|got|kob2?k?|mon|pce|scm|sht?|[tw]gr|vrd)-[ad]?[lw][0125][09]b?|605hw|bg2-u03|(?:gem|fdr|m2|ple|t1)-[7a]0[1-4][lu]|t1-a2[13][lw]|mediapad[\w\. ]*(?= bui|\)))\b(?!.+d\/s)"#,
        ],
        props: &[Capture(Model), Const(Vendor, "Huawei"), Const(Type, "tablet")],
    },
    RuleSrc {
        patterns: &[
            r#"(?:huawei)([-\w ]+)[;\)]"#,
            r#"\b(nexus 6p|\w{2,4}e?-[atu]?[ln][\dx][012359c][adn]?)\b(?!.+d\/s)"#,
        ],
        props: &[Capture(Model), Const(Vendor, "Huawei"), Const(Type, "mobile")],
    },
    RuleSrc {
        patterns: &[
            r#"oid[^\)]+; (2[\dbc]{4}(182|283|rp\w{2})[cgl]|m2105k81a?c)(?: bui|\))"#,
            r#"\b((?:red)?mi[-_ ]?pad[\w- ]*)(?: bui|\))"#,
        ],
        props: &[Replace(Model, Rep::ReplaceAll { from: '_', to: " " }), Const(Vendor, "Xiaomi"), Const(Type, "tablet")],
    },
    RuleSrc {
        patterns: &[
            r#"\b(poco[\w ]+|m2\d{3}j\d\d[a-z]{2})(?: bui|\))"#,
            r#"\b; (\w+) build\/hm\1"#,
            r#"\b(hm[-_ ]?note?[_ ]?(?:\d\w)?) bui"#,
            r#"\b(redmi[\-_ ]?(?:note|k)?[\w_ ]+)(?: bui|\))"#,
            r#"oid[^\)]+; (m?[12][0-389][01]\w{3,6}[c-y])( bui|; wv|\))"#,
            r#"\b(mi[-_ ]?(?:a\d|one|one[_ ]plus|note lte|max|cc)?[_ ]?(?:\d?\w?)[_ ]?(?:plus|se|lite|pro)?)(?: bui|\))"#,
            r#" ([\w ]+) miui\/v?\d"#,
        ],
        props: &[Replace(Model, Rep::ReplaceAll { from: '_', to: " " }), Const(Vendor, "Xiaomi"), Const(Type, "mobile")],
    },
    RuleSrc {
        patterns: &[
            r#"; (\w+) bui.+ oppo"#,
            r#"\b(cph[12]\d{3}|p(?:af|c[al]|d\w|e[ar])[mt]\d0|x9007|a101op)\b"#,
        ],
        props: &[Capture(Model), Const(Vendor, "OPPO"), Const(Type, "mobile")],
    },
    RuleSrc {
        patterns: &[
            r#"\b(opd2(\d{3}a?))(?: bui|\))"#,
        ],
        props: &[Capture(Model), Map(Vendor, &STR_MAP_0), Const(Type, "tablet")],
    },
    RuleSrc {
        patterns: &[
            r#"(vivo (5r?|6|8l?|go|one|s|x[il]?[2-4]?)[\w\+ ]*)(?: bui|\))"#,
        ],
        props: &[Capture(Model), Const(Vendor, "BLU"), Const(Type, "mobile")],
    },
    RuleSrc {
        patterns: &[
            r#"; vivo (\w+)(?: bui|\))"#,
            r#"\b(v[12]\d{3}\w?[at])(?: bui|;)"#,
        ],
        props: &[Capture(Model), Const(Vendor, "Vivo"), Const(Type, "mobile")],
    },
    RuleSrc {
        patterns: &[
            r#"\b(rmx[1-3]\d{3})(?: bui|;|\))"#,
        ],
        props: &[Capture(Model), Const(Vendor, "Realme"), Const(Type, "mobile")],
    },
    RuleSrc {
        patterns: &[
            r#"\b(milestone|droid(?:[2-4x]| (?:bionic|x2|pro|razr))?:?( 4g)?)\b[\w ]+build\/"#,
            r#"\bmot(?:orola)?[- ](\w*)"#,
            r#"((?:moto(?! 360)[\w\(\) ]+|xt\d{3,4}|nexus 6)(?= bui|\)))"#,
        ],
        props: &[Capture(Model), Const(Vendor, "Motorola"), Const(Type, "mobile")],
    },
    RuleSrc {
        patterns: &[
            r#"\b(mz60\d|xoom[2 ]{0,2}) build\/"#,
        ],
        props: &[Capture(Model), Const(Vendor, "Motorola"), Const(Type, "tablet")],
    },
    RuleSrc {
        patterns: &[
            r#"((?=lg)?[vl]k\-?\d{3}) bui| 3\.[-\w; ]{10}lg?-([06cv9]{3,4})"#,
        ],
        props: &[Capture(Model), Const(Vendor, "LG"), Const(Type, "tablet")],
    },
    RuleSrc {
        patterns: &[
            r#"(lm(?:-?f100[nv]?|-[\w\.]+)(?= bui|\))|nexus [45])"#,
            r#"\blg[-e;\/ ]+(?!.*(?:browser|netcast|android tv|watch))(\w+)"#,
            r#"\blg-?([\d\w]+) bui"#,
        ],
        props: &[Capture(Model), Const(Vendor, "LG"), Const(Type, "mobile")],
    },
    RuleSrc {
        patterns: &[
            r#"(ideatab[-\w ]+|602lv|d-42a|a101lv|a2109a|a3500-hv|s[56]000|pb-6505[my]|tb-?x?\d{3,4}(?:f[cu]|xu|[av])|yt\d?-[jx]?\d+[lfmx])( bui|;|\)|\/)"#,
            r#"lenovo ?(b[68]0[08]0-?[hf]?|tab(?:[\w- ]+?)|tb[\w-]{6,7})( bui|;|\)|\/)"#,
        ],
        props: &[Capture(Model), Const(Vendor, "Lenovo"), Const(Type, "tablet")],
    },
    RuleSrc {
        patterns: &[
            r#"(nokia) (t[12][01])"#,
        ],
        props: &[Capture(Vendor), Capture(Model), Const(Type, "tablet")],
    },
    RuleSrc {
        patterns: &[
            r#"(?:maemo|nokia).*(n900|lumia \d+|rm-\d+)"#,
            r#"nokia[-_ ]?(([-\w\. ]*))"#,
        ],
        props: &[Replace(Model, Rep::ReplaceAll { from: '_', to: " " }), Const(Type, "mobile"), Const(Vendor, "Nokia")],
    },
    RuleSrc {
        patterns: &[
            r#"(pixel (c|tablet))\b"#,
        ],
        props: &[Capture(Model), Const(Vendor, "Google"), Const(Type, "tablet")],
    },
    RuleSrc {
        patterns: &[
            r#"droid.+; (pixel[\daxl ]{0,6})(?: bui|\))"#,
        ],
        props: &[Capture(Model), Const(Vendor, "Google"), Const(Type, "mobile")],
    },
    RuleSrc {
        patterns: &[
            r#"droid.+; (a?\d[0-2]{2}so|[c-g]\d{4}|so[-gl]\w+|xq-a\w[4-7][12])(?= bui|\).+chrome\/(?![1-6]{0,1}\d\.))"#,
        ],
        props: &[Capture(Model), Const(Vendor, "Sony"), Const(Type, "mobile")],
    },
    RuleSrc {
        patterns: &[
            r#"sony tablet [ps]"#,
            r#"\b(?:sony)?sgp\w+(?: bui|\))"#,
        ],
        props: &[Const(Model, "Xperia Tablet"), Const(Vendor, "Sony"), Const(Type, "tablet")],
    },
    RuleSrc {
        patterns: &[
            r#" (kb2005|in20[12]5|be20[12][59])\b"#,
            r#"(?:one)?(?:plus)? (a\d0\d\d)(?: b|\))"#,
        ],
        props: &[Capture(Model), Const(Vendor, "OnePlus"), Const(Type, "mobile")],
    },
    RuleSrc {
        patterns: &[
            r#"(alexa)webm"#,
            r#"(kf[a-z]{2}wi|aeo(?!bc)\w\w)( bui|\))"#,
            r#"(kf[a-z]+)( bui|\)).+silk\/"#,
        ],
        props: &[Capture(Model), Const(Vendor, "Amazon"), Const(Type, "tablet")],
    },
    RuleSrc {
        patterns: &[
            r#"((?:sd|kf)[0349hijorstuw]+)( bui|\)).+silk\/"#,
        ],
        props: &[Replace(Model, Rep::WrapLines { prefix: "Fire Phone ", suffix: "", global: true }), Const(Vendor, "Amazon"), Const(Type, "mobile")],
    },
    RuleSrc {
        patterns: &[
            r#"(playbook);[-\w\),; ]+(rim)"#,
        ],
        props: &[Capture(Model), Capture(Vendor), Const(Type, "tablet")],
    },
    RuleSrc {
        patterns: &[
            r#"\b((?:bb[a-f]|st[hv])100-\d)"#,
            r#"\(bb10; (\w+)"#,
        ],
        props: &[Capture(Model), Const(Vendor, "BlackBerry"), Const(Type, "mobile")],
    },
    RuleSrc {
        patterns: &[
            r#"(?:\b|asus_)(transfo[prime ]{4,10} \w+|eeepc|slider \w+|nexus 7|padfone|p00[cj])"#,
        ],
        props: &[Capture(Model), Const(Vendor, "ASUS"), Const(Type, "tablet")],
    },
    RuleSrc {
        patterns: &[
            r#" (z[bes]6[027][012][km][ls]|zenfone \d\w?)\b"#,
        ],
        props: &[Capture(Model), Const(Vendor, "ASUS"), Const(Type, "mobile")],
    },
    RuleSrc {
        patterns: &[
            r#"(nexus 9)"#,
        ],
        props: &[Capture(Model), Const(Vendor, "HTC"), Const(Type, "tablet")],
    },
    RuleSrc {
        patterns: &[
            r#"(htc)[-;_ ]{1,2}([\w ]+(?=\)| bui)|\w+)"#,
            r#"(zte)[- ]([\w ]+?)(?: bui|\/|\))"#,
            r#"(alcatel|geeksphone|nexian|panasonic(?!(?:;|\.))|sony(?!-bra))[-_ ]?([-\w]*)"#,
        ],
        props: &[Capture(Vendor), Replace(Model, Rep::ReplaceAll { from: '_', to: " " }), Const(Type, "mobile")],
    },
    RuleSrc {
        patterns: &[
            r#"tcl (xess p17aa)"#,
            r#"droid [\w\.]+; ((?:8[14]9[16]|9(?:0(?:48|60|8[01])|1(?:3[27]|66)|2(?:6[69]|9[56])|466))[gqswx])(_\w(\w|\w\w))?(\)| bui)"#,
        ],
        props: &[Capture(Model), Const(Vendor, "TCL"), Const(Type, "tablet")],
    },
    RuleSrc {
        patterns: &[
            r#"droid [\w\.]+; (418(?:7d|8v)|5087z|5102l|61(?:02[dh]|25[adfh]|27[ai]|56[dh]|59k|65[ah])|a509dl|t(?:43(?:0w|1[adepqu])|50(?:6d|7[adju])|6(?:09dl|10k|12b|71[efho]|76[hjk])|7(?:66[ahju]|67[hw]|7[045][bh]|71[hk]|73o|76[ho]|79w|81[hks]?|82h|90[bhsy]|99b)|810[hs]))(_\w(\w|\w\w))?(\)| bui)"#,
        ],
        props: &[Capture(Model), Const(Vendor, "TCL"), Const(Type, "mobile")],
    },
    RuleSrc {
        patterns: &[
            r#"(itel) ((\w+))"#,
        ],
        props: &[Lower(Vendor), Capture(Model), Map(Type, &STR_MAP_1)],
    },
    RuleSrc {
        patterns: &[
            r#"droid.+; ([ab][1-7]-?[0178a]\d\d?)"#,
        ],
        props: &[Capture(Model), Const(Vendor, "Acer"), Const(Type, "tablet")],
    },
    RuleSrc {
        patterns: &[
            r#"droid.+; (m[1-5] note) bui"#,
            r#"\bmz-([-\w]{2,})"#,
        ],
        props: &[Capture(Model), Const(Vendor, "Meizu"), Const(Type, "mobile")],
    },
    RuleSrc {
        patterns: &[
            r#"; ((?:power )?armor(?:[\w ]{0,8}))(?: bui|\))"#,
        ],
        props: &[Capture(Model), Const(Vendor, "Ulefone"), Const(Type, "mobile")],
    },
    RuleSrc {
        patterns: &[
            r#"; (energy ?\w+)(?: bui|\))"#,
            r#"; energizer ([\w ]+)(?: bui|\))"#,
        ],
        props: &[Capture(Model), Const(Vendor, "Energizer"), Const(Type, "mobile")],
    },
    RuleSrc {
        patterns: &[
            r#"; cat (b35);"#,
            r#"; (b15q?|s22 flip|s48c|s62 pro)(?: bui|\))"#,
        ],
        props: &[Capture(Model), Const(Vendor, "Cat"), Const(Type, "mobile")],
    },
    RuleSrc {
        patterns: &[
            r#"((?:new )?andromax[\w- ]+)(?: bui|\))"#,
        ],
        props: &[Capture(Model), Const(Vendor, "Smartfren"), Const(Type, "mobile")],
    },
    RuleSrc {
        patterns: &[
            r#"droid.+; (a(?:015|06[35]|142p?))"#,
        ],
        props: &[Capture(Model), Const(Vendor, "Nothing"), Const(Type, "mobile")],
    },
    RuleSrc {
        patterns: &[
            r#"; (x67 5g|tikeasy \w+|ac[1789]\d\w+)( b|\))"#,
            r#"archos ?(5|gamepad2?|([\w ]*[t1789]|hello) ?\d+[\w ]*)( b|\))"#,
        ],
        props: &[Capture(Model), Const(Vendor, "Archos"), Const(Type, "tablet")],
    },
    RuleSrc {
        patterns: &[
            r#"archos ([\w ]+)( b|\))"#,
            r#"; (ac[3-6]\d\w{2,8})( b|\))"#,
        ],
        props: &[Capture(Model), Const(Vendor, "Archos"), Const(Type, "mobile")],
    },
    RuleSrc {
        patterns: &[
            r#"(imo) (tab \w+)"#,
            r#"(infinix) (x1101b?)"#,
        ],
        props: &[Capture(Vendor), Capture(Model), Const(Type, "tablet")],
    },
    RuleSrc {
        patterns: &[
            r#"(blackberry|benq|palm(?=\-)|sonyericsson|acer|asus(?! zenw)|dell|jolla|meizu|motorola|polytron|infinix|tecno|micromax|advan)[-_ ]?([-\w]*)"#,
            r#"; (blu|hmd|imo|tcl)[_ ]([\w\+ ]+?)(?: bui|\)|; r)"#,
            r#"(hp) ([\w ]+\w)"#,
            r#"(microsoft); (lumia[\w ]+)"#,
            r#"(lenovo)[-_ ]?([-\w ]+?)(?: bui|\)|\/)"#,
            r#"(oppo) ?([\w ]+) bui"#,
        ],
        props: &[Capture(Vendor), Capture(Model), Const(Type, "mobile")],
    },
    RuleSrc {
        patterns: &[
            r#"(kobo)\s(ereader|touch)"#,
            r#"(hp).+(touchpad(?!.+tablet)|tablet)"#,
            r#"(kindle)\/([\w\.]+)"#,
        ],
        props: &[Capture(Vendor), Capture(Model), Const(Type, "tablet")],
    },
    RuleSrc {
        patterns: &[
            r#"(surface duo)"#,
        ],
        props: &[Capture(Model), Const(Vendor, "Microsoft"), Const(Type, "tablet")],
    },
    RuleSrc {
        patterns: &[
            r#"droid [\d\.]+; (fp\du?)(?: b|\))"#,
        ],
        props: &[Capture(Model), Const(Vendor, "Fairphone"), Const(Type, "mobile")],
    },
    RuleSrc {
        patterns: &[
            r#"((?:tegranote|shield t(?!.+d tv))[\w- ]*?)(?: b|\))"#,
        ],
        props: &[Capture(Model), Const(Vendor, "Nvidia"), Const(Type, "tablet")],
    },
    RuleSrc {
        patterns: &[
            r#"(sprint) (\w+)"#,
        ],
        props: &[Capture(Vendor), Capture(Model), Const(Type, "mobile")],
    },
    RuleSrc {
        patterns: &[
            r#"(kin\.[onetw]{3})"#,
        ],
        props: &[Replace(Model, Rep::ReplaceAll { from: '.', to: " " }), Const(Vendor, "Microsoft"), Const(Type, "mobile")],
    },
    RuleSrc {
        patterns: &[
            r#"droid.+; ([c6]+|et5[16]|mc[239][23]x?|vc8[03]x?)\)"#,
        ],
        props: &[Capture(Model), Const(Vendor, "Zebra"), Const(Type, "tablet")],
    },
    RuleSrc {
        patterns: &[
            r#"droid.+; (ec30|ps20|tc[2-8]\d[kx])\)"#,
        ],
        props: &[Capture(Model), Const(Vendor, "Zebra"), Const(Type, "mobile")],
    },
    RuleSrc {
        patterns: &[
            r#"smart-tv.+(samsung)"#,
        ],
        props: &[Capture(Vendor), Const(Type, "smarttv")],
    },
    RuleSrc {
        patterns: &[
            r#"hbbtv.+maple;(\d+)"#,
        ],
        props: &[Replace(Model, Rep::Prepend("SmartTV")), Const(Vendor, "Samsung"), Const(Type, "smarttv")],
    },
    RuleSrc {
        patterns: &[
            r#"tcast.+(lg)e?. ([-\w]+)"#,
        ],
        props: &[Capture(Vendor), Capture(Model), Const(Type, "smarttv")],
    },
    RuleSrc {
        patterns: &[
            r#"(nux; netcast.+smarttv|lg (netcast\.tv-201\d|android tv))"#,
        ],
        props: &[Const(Vendor, "LG"), Const(Type, "smarttv")],
    },
    RuleSrc {
        patterns: &[
            r#"(apple) ?tv"#,
        ],
        props: &[Capture(Vendor), Const(Model, "Apple TV"), Const(Type, "smarttv")],
    },
    RuleSrc {
        patterns: &[
            r#"crkey.*devicetype\/chromecast"#,
        ],
        props: &[Const(Model, "Chromecast Third Generation"), Const(Vendor, "Google"), Const(Type, "smarttv")],
    },
    RuleSrc {
        patterns: &[
            r#"crkey.*devicetype\/([^/]*)"#,
        ],
        props: &[Replace(Model, Rep::Prepend("Chromecast ")), Const(Vendor, "Google"), Const(Type, "smarttv")],
    },
    RuleSrc {
        patterns: &[
            r#"fuchsia.*crkey"#,
        ],
        props: &[Const(Model, "Chromecast Nest Hub"), Const(Vendor, "Google"), Const(Type, "smarttv")],
    },
    RuleSrc {
        patterns: &[
            r#"crkey"#,
        ],
        props: &[Const(Model, "Chromecast"), Const(Vendor, "Google"), Const(Type, "smarttv")],
    },
    RuleSrc {
        patterns: &[
            r#"(portaltv)"#,
        ],
        props: &[Capture(Model), Const(Vendor, "Facebook"), Const(Type, "smarttv")],
    },
    RuleSrc {
        patterns: &[
            r#"droid.+aft(\w+)( bui|\))"#,
        ],
        props: &[Capture(Model), Const(Vendor, "Amazon"), Const(Type, "smarttv")],
    },
    RuleSrc {
        patterns: &[
            r#"(shield \w+ tv)"#,
        ],
        props: &[Capture(Model), Const(Vendor, "Nvidia"), Const(Type, "smarttv")],
    },
    RuleSrc {
        patterns: &[
            r#"\(dtv[\);].+(aquos)"#,
            r#"(aquos-tv[\w ]+)\)"#,
        ],
        props: &[Capture(Model), Const(Vendor, "Sharp"), Const(Type, "smarttv")],
    },
    RuleSrc {
        patterns: &[
            r#"(bravia[\w ]+)( bui|\))"#,
        ],
        props: &[Capture(Model), Const(Vendor, "Sony"), Const(Type, "smarttv")],
    },
    RuleSrc {
        patterns: &[
            r#"(mi(tv|box)-?\w+) bui"#,
        ],
        props: &[Capture(Model), Const(Vendor, "Xiaomi"), Const(Type, "smarttv")],
    },
    RuleSrc {
        patterns: &[
            r#"Hbbtv.*(technisat) (.*);"#,
        ],
        props: &[Capture(Vendor), Capture(Model), Const(Type, "smarttv")],
    },
    RuleSrc {
        patterns: &[
            r#"\b(roku)[\dx]*[\)\/]((?:dvp-)?[\d\.]*)"#,
            r#"hbbtv\/\d+\.\d+\.\d+ +\([\w\+ ]*; *([\w\d][^;]*);([^;]*)"#,
        ],
        props: &[Trim(Vendor), Trim(Model), Const(Type, "smarttv")],
    },
    RuleSrc {
        patterns: &[
            r#"droid.+; ([\w- ]+) (?:android tv|smart[- ]?tv)"#,
        ],
        props: &[Capture(Model), Const(Type, "smarttv")],
    },
    RuleSrc {
        patterns: &[
            r#"\b(android tv|smart[- ]?tv|opera tv|tv; rv:)\b"#,
        ],
        props: &[Const(Type, "smarttv")],
    },
    RuleSrc {
        patterns: &[
            r#"(ouya)"#,
            r#"(nintendo) (\w+)"#,
        ],
        props: &[Capture(Vendor), Capture(Model), Const(Type, "console")],
    },
    RuleSrc {
        patterns: &[
            r#"droid.+; (shield)( bui|\))"#,
        ],
        props: &[Capture(Model), Const(Vendor, "Nvidia"), Const(Type, "console")],
    },
    RuleSrc {
        patterns: &[
            r#"(playstation \w+)"#,
        ],
        props: &[Capture(Model), Const(Vendor, "Sony"), Const(Type, "console")],
    },
    RuleSrc {
        patterns: &[
            r#"\b(xbox(?: one)?(?!; xbox))[\); ]"#,
        ],
        props: &[Capture(Model), Const(Vendor, "Microsoft"), Const(Type, "console")],
    },
    RuleSrc {
        patterns: &[
            r#"\b(sm-[lr]\d\d[0156][fnuw]?s?|gear live)\b"#,
        ],
        props: &[Capture(Model), Const(Vendor, "Samsung"), Const(Type, "wearable")],
    },
    RuleSrc {
        patterns: &[
            r#"((pebble))app"#,
            r#"(asus|google|lg|oppo) ((pixel |zen)?watch[\w ]*)( bui|\))"#,
        ],
        props: &[Capture(Vendor), Capture(Model), Const(Type, "wearable")],
    },
    RuleSrc {
        patterns: &[
            r#"(ow(?:19|20)?we?[1-3]{1,3})"#,
        ],
        props: &[Capture(Model), Const(Vendor, "OPPO"), Const(Type, "wearable")],
    },
    RuleSrc {
        patterns: &[
            r#"(watch)(?: ?os[,\/]|\d,\d\/)[\d\.]+"#,
        ],
        props: &[Capture(Model), Const(Vendor, "Apple"), Const(Type, "wearable")],
    },
    RuleSrc {
        patterns: &[
            r#"(opwwe\d{3})"#,
        ],
        props: &[Capture(Model), Const(Vendor, "OnePlus"), Const(Type, "wearable")],
    },
    RuleSrc {
        patterns: &[
            r#"(moto 360)"#,
        ],
        props: &[Capture(Model), Const(Vendor, "Motorola"), Const(Type, "wearable")],
    },
    RuleSrc {
        patterns: &[
            r#"(smartwatch 3)"#,
        ],
        props: &[Capture(Model), Const(Vendor, "Sony"), Const(Type, "wearable")],
    },
    RuleSrc {
        patterns: &[
            r#"(g watch r)"#,
        ],
        props: &[Capture(Model), Const(Vendor, "LG"), Const(Type, "wearable")],
    },
    RuleSrc {
        patterns: &[
            r#"droid.+; (wt63?0{2,3})\)"#,
        ],
        props: &[Capture(Model), Const(Vendor, "Zebra"), Const(Type, "wearable")],
    },
    RuleSrc {
        patterns: &[
            r#"droid.+; (glass) \d"#,
        ],
        props: &[Capture(Model), Const(Vendor, "Google"), Const(Type, "xr")],
    },
    RuleSrc {
        patterns: &[
            r#"(pico) (4|neo3(?: link|pro)?)"#,
        ],
        props: &[Capture(Vendor), Capture(Model), Const(Type, "xr")],
    },
    RuleSrc {
        patterns: &[
            r#"(quest( \d| pro)?s?).+vr"#,
        ],
        props: &[Capture(Model), Const(Vendor, "Facebook"), Const(Type, "xr")],
    },
    RuleSrc {
        patterns: &[
            r#"(tesla)(?: qtcarbrowser|\/[-\w\.]+)"#,
        ],
        props: &[Capture(Vendor), Const(Type, "embedded")],
    },
    RuleSrc {
        patterns: &[
            r#"(aeobc)\b"#,
        ],
        props: &[Capture(Model), Const(Vendor, "Amazon"), Const(Type, "embedded")],
    },
    RuleSrc {
        patterns: &[
            r#"(homepod).+mac os"#,
        ],
        props: &[Capture(Model), Const(Vendor, "Apple"), Const(Type, "embedded")],
    },
    RuleSrc {
        patterns: &[
            r#"windows iot"#,
        ],
        props: &[Const(Type, "embedded")],
    },
    RuleSrc {
        patterns: &[
            r#"droid .+?; ([^;]+?)(?: bui|; wv\)|\) applew).+?(mobile|vr|\d) safari"#,
        ],
        props: &[Capture(Model), Map(Type, &STR_MAP_2)],
    },
    RuleSrc {
        patterns: &[
            r#"\b((tablet|tab)[;\/]|focus\/\d(?!.+mobile))"#,
        ],
        props: &[Const(Type, "tablet")],
    },
    RuleSrc {
        patterns: &[
            r#"(phone|mobile(?:[;\/]| [ \w\/\.]*safari)|pda(?=.+windows ce))"#,
        ],
        props: &[Const(Type, "mobile")],
    },
    RuleSrc {
        patterns: &[
            r#"droid .+?; ([\w\. -]+)( bui|\))"#,
        ],
        props: &[Capture(Model), Const(Vendor, "Generic")],
    },
];

pub(super) static ENGINE: &[RuleSrc] = &[
    RuleSrc {
        patterns: &[
            r#"windows.+ edge\/([\w\.]+)"#,
        ],
        props: &[Capture(Version), Const(Name, "EdgeHTML")],
    },
    RuleSrc {
        patterns: &[
            r#"(arkweb)\/([\w\.]+)"#,
        ],
        props: &[Capture(Name), Capture(Version)],
    },
    RuleSrc {
        patterns: &[
            r#"webkit\/537\.36.+chrome\/(?!27)([\w\.]+)"#,
        ],
        props: &[Capture(Version), Const(Name, "Blink")],
    },
    RuleSrc {
        patterns: &[
            r#"(presto)\/([\w\.]+)"#,
            r#"(webkit|trident|netfront|netsurf|amaya|lynx|w3m|goanna|servo)\/([\w\.]+)"#,
            r#"ekioh(flow)\/([\w\.]+)"#,
            r#"(khtml|tasman|links)[\/ ]\(?([\w\.]+)"#,
            r#"(icab)[\/ ]([23]\.[\d\.]+)"#,
            r#"\b(libweb)"#,
        ],
        props: &[Capture(Name), Capture(Version)],
    },
    RuleSrc {
        patterns: &[
            r#"ladybird\/"#,
        ],
        props: &[Const(Name, "LibWeb")],
    },
    RuleSrc {
        patterns: &[
            r#"rv\:([\w\.]{1,9})\b.+(gecko)"#,
        ],
        props: &[Capture(Version), Capture(Name)],
    },
];

pub(super) static OS: &[RuleSrc] = &[
    RuleSrc {
        patterns: &[
            r#"microsoft (windows) (vista|xp)"#,
        ],
        props: &[Capture(Name), Capture(Version)],
    },
    RuleSrc {
        patterns: &[
            r#"(windows (?:phone(?: os)?|mobile|iot))[\/ ]?([\d\.\w ]*)"#,
        ],
        props: &[Capture(Name), Map(Version, &WINDOWS_VERSION_MAP)],
    },
    RuleSrc {
        patterns: &[
            r#"windows nt 6\.2; (arm)"#,
            r#"windows[\/ ]([ntce\d\. ]+\w)(?!.+xbox)"#,
            r#"(?:win(?=3|9|n)|win 9x )([nt\d\.]+)"#,
        ],
        props: &[Map(Version, &WINDOWS_VERSION_MAP), Const(Name, "Windows")],
    },
    RuleSrc {
        patterns: &[
            r#"[adehimnop]{4,7}\b(?:.*os ([\w]+) like mac|; opera)"#,
            r#"(?:ios;fbsv\/|iphone.+ios[\/ ])([\d\.]+)"#,
            r#"cfnetwork\/.+darwin"#,
        ],
        props: &[Replace(Version, Rep::ReplaceAll { from: '_', to: "." }), Const(Name, "iOS")],
    },
    RuleSrc {
        patterns: &[
            r#"(mac os x) ?([\w\. ]*)"#,
            r#"(macintosh|mac_powerpc\b)(?!.+haiku)"#,
        ],
        props: &[Const(Name, "macOS"), Replace(Version, Rep::ReplaceAll { from: '_', to: "." })],
    },
    RuleSrc {
        patterns: &[
            r#"android ([\d\.]+).*crkey"#,
        ],
        props: &[Capture(Version), Const(Name, "Chromecast Android")],
    },
    RuleSrc {
        patterns: &[
            r#"fuchsia.*crkey\/([\d\.]+)"#,
        ],
        props: &[Capture(Version), Const(Name, "Chromecast Fuchsia")],
    },
    RuleSrc {
        patterns: &[
            r#"crkey\/([\d\.]+).*devicetype\/smartspeaker"#,
        ],
        props: &[Capture(Version), Const(Name, "Chromecast SmartSpeaker")],
    },
    RuleSrc {
        patterns: &[
            r#"linux.*crkey\/([\d\.]+)"#,
        ],
        props: &[Capture(Version), Const(Name, "Chromecast Linux")],
    },
    RuleSrc {
        patterns: &[
            r#"crkey\/([\d\.]+)"#,
        ],
        props: &[Capture(Version), Const(Name, "Chromecast")],
    },
    RuleSrc {
        patterns: &[
            r#"droid ([\w\.]+)\b.+(android[- ]x86|harmonyos)"#,
        ],
        props: &[Capture(Version), Capture(Name)],
    },
    RuleSrc {
        patterns: &[
            r#"(ubuntu) ([\w\.]+) like android"#,
        ],
        props: &[Replace(Name, Rep::WrapLines { prefix: "", suffix: " Touch", global: false }), Capture(Version)],
    },
    RuleSrc {
        patterns: &[
            r#"(android|bada|blackberry|kaios|maemo|meego|openharmony|qnx|rim tablet os|sailfish|series40|symbian|tizen|webos)\w*[-\/\.; ]?([\d\.]*)"#,
        ],
        props: &[Capture(Name), Capture(Version)],
    },
    RuleSrc {
        patterns: &[
            r#"\(bb(10);"#,
        ],
        props: &[Capture(Version), Const(Name, "BlackBerry")],
    },
    RuleSrc {
        patterns: &[
            r#"(?:symbian ?os|symbos|s60(?=;)|series ?60)[-\/ ]?([\w\.]*)"#,
        ],
        props: &[Capture(Version), Const(Name, "Symbian")],
    },
    RuleSrc {
        patterns: &[
            r#"mozilla\/[\d\.]+ \((?:mobile|tablet|tv|mobile; [\w ]+); rv:.+ gecko\/([\w\.]+)"#,
        ],
        props: &[Capture(Version), Const(Name, "Firefox OS")],
    },
    RuleSrc {
        patterns: &[
            r#"web0s;.+rt(tv)"#,
            r#"\b(?:hp)?wos(?:browser)?\/([\w\.]+)"#,
        ],
        props: &[Capture(Version), Const(Name, "webOS")],
    },
    RuleSrc {
        patterns: &[
            r#"watch(?: ?os[,\/]|\d,\d\/)([\d\.]+)"#,
        ],
        props: &[Capture(Version), Const(Name, "watchOS")],
    },
    RuleSrc {
        patterns: &[
            r#"(cros) [\w]+(?:\)| ([\w\.]+)\b)"#,
        ],
        props: &[Const(Name, "Chrome OS"), Capture(Version)],
    },
    RuleSrc {
        patterns: &[
            r#"panasonic;(viera)"#,
            r#"(netrange)mmh"#,
            r#"(nettv)\/(\d+\.[\w\.]+)"#,
            r#"(nintendo|playstation) (\w+)"#,
            r#"(xbox); +xbox ([^\);]+)"#,
            r#"(pico) .+os([\w\.]+)"#,
            r#"\b(joli|palm)\b ?(?:os)?\/?([\w\.]*)"#,
            r#"(mint)[\/\(\) ]?(\w*)"#,
            r#"(mageia|vectorlinux)[; ]"#,
            r#"([kxln]?ubuntu|debian|suse|opensuse|gentoo|arch(?= linux)|slackware|fedora|mandriva|centos|pclinuxos|red ?hat|zenwalk|linpus|raspbian|plan 9|minix|risc os|contiki|deepin|manjaro|elementary os|sabayon|linspire)(?: gnu\/linux)?(?: enterprise)?(?:[- ]linux)?(?:-gnu)?[-\/ ]?(?!chrom|package)([-\w\.]*)"#,
            r#"(hurd|linux)(?: arm\w*| x86\w*| ?)([\w\.]*)"#,
            r#"(gnu) ?([\w\.]*)"#,
            r#"\b([-frentopcghs]{0,5}bsd|dragonfly)[\/ ]?(?!amd|[ix346]{1,2}86)([\w\.]*)"#,
            r#"(haiku) (\w+)"#,
        ],
        props: &[Capture(Name), Capture(Version)],
    },
    RuleSrc {
        patterns: &[
            r#"(sunos) ?([\w\.\d]*)"#,
        ],
        props: &[Const(Name, "Solaris"), Capture(Version)],
    },
    RuleSrc {
        patterns: &[
            r#"((?:open)?solaris)[-\/ ]?([\w\.]*)"#,
            r#"(aix) ((\d)(?=\.|\)| )[\w\.])*"#,
            r#"\b(beos|os\/2|amigaos|morphos|openvms|fuchsia|hp-ux|serenityos)"#,
            r#"(unix) ?([\w\.]*)"#,
        ],
        props: &[Capture(Name), Capture(Version)],
    },
];

pub(super) static STR_MAP_0: StrMap = StrMap {
    entries: &[("OnePlus", &["304", "403", "203"]), ("*", &["OPPO"])],
    fallback: Some(Some("OPPO")),
};

pub(super) static STR_MAP_1: StrMap = StrMap {
    entries: &[("tablet", &["p10001l", "w7001"]), ("*", &["mobile"])],
    fallback: Some(Some("mobile")),
};

pub(super) static STR_MAP_2: StrMap = StrMap {
    entries: &[("mobile", &["Mobile"]), ("xr", &["VR"]), ("*", &["tablet"])],
    fallback: Some(Some("tablet")),
};

pub(super) static WINDOWS_VERSION_MAP: StrMap = StrMap {
    entries: &[("7", &["NT 6.1"]), ("8", &["NT 6.2"]), ("10", &["NT 6.4", "NT 10.0"]), ("2000", &["NT 5.0"]), ("ME", &["4.90"]), ("NT 3.11", &["NT3.51"]), ("NT 4.0", &["NT4.0"]), ("XP", &["NT 5.1", "NT 5.2"]), ("Vista", &["NT 6.0"]), ("8.1", &["NT 6.3"]), ("RT", &["ARM"])],
    fallback: None,
};
