// Emits the ASCII-uppercased ICU time zone IDs that Intl.DateTimeFormat accepts,
// sorted for binary search. Source: the "Names" table of ICU's zoneinfo64 for the
// tzdata Node bundles, filtered through Node itself so the list is exactly the
// accepted set.
import { readFileSync } from "node:fs";

const names = JSON.parse(readFileSync(process.argv[2], "utf8"));
const accepted = names.filter(name => {
  try {
    Intl.DateTimeFormat(undefined, { timeZone: name });
    return true;
  } catch {
    return false;
  }
});
const upper = [...new Set(accepted.map(name => name.replace(/[a-z]/g, c => c.toUpperCase())))].sort((a, b) =>
  a < b ? -1 : a > b ? 1 : 0
);
process.stdout.write(
  `//! Generated by parity/analytics/gen_zones.mjs from ICU zoneinfo64 Names (tz ${process.versions.tz}) under Node ${process.version}.\n` +
    `//! ${accepted.length} of ${names.length} IDs are accepted by Intl.DateTimeFormat. Do not edit by hand.\n\n` +
    `pub(crate) const UPPERCASE_ZONE_IDS: [&str; ${upper.length}] = [\n` +
    upper.map(name => `    ${JSON.stringify(name)},`).join("\n") +
    "\n];\n"
);
