// Emits Rust range tables for the Unicode properties V8's RegExp capture-group
// name parser consults (ID_Start, ID_Continue), plus Zs for the date parser.
const ranges = re => {
  const out = [];
  let start = -1;
  for (let cp = 0; cp <= 0x110000; cp++) {
    const hit = cp < 0x110000 && re.test(String.fromCodePoint(cp));
    if (hit && start < 0) start = cp;
    if (!hit && start >= 0) {
      out.push([start, cp - 1]);
      start = -1;
    }
  }
  return out;
};
const fmt = (name, list) =>
  `pub(crate) const ${name}: &[(u32, u32)] = &[\n${list.map(([a, b]) => `    (0x${a.toString(16).toUpperCase()}, 0x${b.toString(16).toUpperCase()}),`).join("\n")}\n];\n`;
const idStart = ranges(/^\p{ID_Start}$/u);
const idContinue = ranges(/^\p{ID_Continue}$/u);
const zs = ranges(/^\p{Zs}$/u);
process.stdout.write(
  `//! Generated by parity/analytics/gen_unicode.mjs from Node ${process.version} (ICU ${process.versions.icu}, Unicode ${process.versions.unicode}).\n` +
    `//! Do not edit by hand.\n\n` +
    fmt("ID_START", idStart) +
    "\n" +
    fmt("ID_CONTINUE", idContinue) +
    "\n" +
    fmt("SPACE_SEPARATOR", zs)
);
