[package]
name = "hygo-backend"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.104"
axum = "0.8.9"
base64 = "0.23.1"
chrono = { version = "0.4.45", features = ["serde"] }
fancy-regex = "0.19.2"
hex = "0.4.3"
hmac = "0.13.0"
httpdate = "1.0.3"
indexmap = "2.14.2"
maxminddb = { version = "0.32.0", features = ["mmap"] }
nanoid = "0.5.0"
percent-encoding = "2.3.2"
rand = "0.10.2"
redis = { version = "1.7.0", features = ["tokio-comp", "connection-manager"] }
regex = "1.13.1"
regress = { version = "0.12.0", features = ["utf16"] }
reqwest = { version = "0.13.5", default-features = false, features = ["json", "query", "rustls"] }
ryu-js = "1.0.3"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = { version = "1.0.151", features = ["preserve_order", "float_roundtrip"] }
sha2 = "0.11.0"
sqlx = { version = "0.8.6", default-features = false, features = ["runtime-tokio", "postgres", "chrono", "uuid", "json", "derive"] }
thiserror = "2.0.20"
tokio = { version = "1.53.1", features = ["full"] }
tower-http = { version = "0.7.1", features = ["trace"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["json", "env-filter"] }
url = "2.5.8"

[dev-dependencies]
flate2 = "1.1"
