//! The recorder's `metadata.pageUrl` as the replay code reads it: `new URL(pageUrl)`
//! for the tracking data, and `parseReplayPageUrl` (recordSessionReplay.ts) for the
//! Site Exclusion Decision, which also accepts a bare path.

use crate::tracking::url_params::url_hostname;

/// `hostname`, `pathname` and `search` of `new URL(input)`, or None where the
/// constructor throws. Hostname acceptance follows `url_hostname`, which corrects
/// the `url` crate where it disagrees with Node's WHATWG parser.
pub fn whatwg_url(input: &str) -> Option<UrlParts> {
    let hostname = url_hostname(input)?;
    let url = url::Url::parse(input).ok()?;
    // `search` is "" for both a missing and an empty query
    let search = url.query().filter(|query| !query.is_empty()).map(|query| format!("?{query}")).unwrap_or_default();
    // The current path percent-encode set includes `^`, which ada encodes and the
    // url crate leaves raw; opaque paths (`mailto:a^b`) use the C0 set in both
    let pathname = if url.cannot_be_a_base() { url.path().to_string() } else { url.path().replace('^', "%5E") };
    Some(UrlParts { hostname, pathname, search })
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct UrlParts {
    pub hostname: String,
    pub pathname: String,
    pub search: String,
}

/// `parseReplayPageUrl`'s result; None stands for `undefined`.
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct ReplayPageUrl {
    pub hostname: Option<String>,
    pub pathname: Option<String>,
    pub querystring: Option<String>,
}

/// `parseReplayPageUrl(pageUrl)`: a full URL gives hostname, pathname and search
/// (with its `?`); a path starting with `/` gives the path before `?`/`#` and the
/// query after the first `?` (without it); anything else gives nothing.
pub fn parse_replay_page_url(page_url: Option<&str>) -> ReplayPageUrl {
    let Some(page_url) = page_url.filter(|url| !url.is_empty()) else {
        return ReplayPageUrl::default();
    };

    if let Some(parts) = whatwg_url(page_url) {
        return ReplayPageUrl {
            hostname: Some(parts.hostname),
            pathname: Some(parts.pathname),
            querystring: Some(parts.search),
        };
    }

    if page_url.starts_with('/') {
        // pageUrl.split(/[?#]/, 1)[0]
        let pathname = page_url.split(['?', '#']).next().unwrap_or_default().to_string();
        // pageUrl.split("#", 1)[0].split(/\?(.*)/s)[1]
        let before_hash = page_url.split('#').next().unwrap_or_default();
        let querystring = before_hash.split_once('?').map(|(_, query)| query.to_string());
        return ReplayPageUrl { hostname: None, pathname: Some(pathname), querystring };
    }

    ReplayPageUrl::default()
}

#[cfg(test)]
mod tests {
    use super::*;

    fn parts(input: &str) -> (Option<&str>, Option<&str>, Option<&str>) {
        let parsed = Box::leak(Box::new(parse_replay_page_url(Some(input))));
        (parsed.hostname.as_deref(), parsed.pathname.as_deref(), parsed.querystring.as_deref())
    }

    // Outputs of parseReplayPageUrl in Node for the same inputs
    #[test]
    fn splits_urls_and_paths_like_node() {
        assert_eq!(parts("https://example.com/admin/users?tab=settings"), (Some("example.com"), Some("/admin/users"), Some("?tab=settings")));
        assert_eq!(parts("https://preview.vercel.app/app"), (Some("preview.vercel.app"), Some("/app"), Some("")));
        assert_eq!(parts("https://a.example/?"), (Some("a.example"), Some("/"), Some("")));
        assert_eq!(parts("HTTPS://ExAmple.COM:443/a b?q=1 2#h"), (Some("example.com"), Some("/a%20b"), Some("?q=1%202")));
        assert_eq!(parts("/pricing?plan=pro#faq"), (None, Some("/pricing"), Some("plan=pro")));
        assert_eq!(parts("/a#x?y"), (None, Some("/a"), None));
        assert_eq!(parts("/a?b?c"), (None, Some("/a"), Some("b?c")));
        assert_eq!(parts("/a?"), (None, Some("/a"), Some("")));
        assert_eq!(parts("//host/path"), (None, Some("//host/path"), None));
        assert_eq!(parts("pricing"), (None, None, None));
        assert_eq!(parse_replay_page_url(Some("")), ReplayPageUrl::default());
        assert_eq!(parse_replay_page_url(None), ReplayPageUrl::default());
    }

    /// Differential fixture: page URLs and Node's parseReplayPageUrl result for each,
    /// generated by parity/replay/gen_urls.mjs.
    #[test]
    fn matches_node_on_generated_page_urls() {
        type Case = (String, Option<String>, Option<String>, Option<String>);
        let cases: Vec<Case> = serde_json::from_str(include_str!("testdata/page_urls.json")).expect("fixture parses");
        assert!(cases.len() > 500);
        let mut mismatches = Vec::new();
        let mut known = 0;
        for (input, hostname, pathname, querystring) in cases {
            let parsed = parse_replay_page_url(Some(&input));
            let expected = ReplayPageUrl { hostname, pathname, querystring };
            if parsed == expected {
                continue;
            }
            // Known: a file: URL whose host needs IDNA or percent-decoding and whose
            // path starts with a backslash keeps an empty segment in ada ("//x") that
            // the url crate drops ("/x"). Only exclusion path matching reads it.
            if input.starts_with("file://") && input.contains("/\\") && parsed.hostname == expected.hostname {
                known += 1;
                continue;
            }
            mismatches.push(format!("{input:?}: node {expected:?}, rust {parsed:?}"));
        }
        assert!(mismatches.is_empty(), "{} mismatches:\n{}", mismatches.len(), mismatches.join("\n"));
        assert!(known <= 2, "{known} file: backslash differences, expected at most 2");
    }
}
